---

- name: Create the minio-user group
  ansible.builtin.group:
    name: minio-user
    state: present

- name: Create the minio-user user
  ansible.builtin.user:
    name: minio-user
    group: minio-user
    shell: /bin/false
    create_home: false
    system: true
    state: present

- name: Download minio
  ansible.builtin.get_url:
    url: "https://dl.min.io/server/minio/release/linux-{{ [ansible_architecture] | map('extract', minio_deb_architecture) | first }}/minio"
    dest: "/usr/local/bin/minio"
    mode: 0755

- name: Add etc/default/minio
  ansible.builtin.copy:
    src: default.minio
    dest: /etc/default/minio
    mode: 0644
    force: false

- name: Add minio systemd unit file
  ansible.builtin.copy:
    src: minio.service
    dest: /usr/lib/systemd/system/minio.service
    mode: 0644

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable minio
  ansible.builtin.systemd:
    name: minio
    enabled: true

...
